trigger:
- main

pool:
  vmImage: 'macOS-latest'

variables:
  # Menggunakan wildcard agar pipeline otomatis mencari file .xcodeproj di root atau sub-folder mana pun
  projectPath: '**/*.xcodeproj' 
  # Mengubah scheme sesuai dengan nama default project pada repositori macagua/HelloWorldSwiftUI
  scheme: 'HelloWorldSwiftUI' 
  sdk: 'iphonesimulator'
  configuration: 'Debug'

steps:
- task: Xcode@5
  displayName: 'Kompilasi iOS - Simulator Target'
  inputs:
    actions: 'build'
    configuration: '$(configuration)'
    sdk: '$(sdk)'
    xcWorkspacePath: '$(projectPath)'
    scheme: '$(scheme)'
    packageApp: false
    useXcpretty: true